{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBInternalNetworkingError","preciseIdentifier":"s:12UBFoundation25UBInternalNetworkingErrorO","text":"UBInternalNetworkingError"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworkingerror\/internal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingError\/internal(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"We cannot provide actionable information to the user. It is likely that something is broken on our end"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UBInternalNetworkingError","preciseIdentifier":"s:12UBFoundation25UBInternalNetworkingErrorO"},{"kind":"text","text":")"}],"title":"UBNetworkingError.internal(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12UBFoundation17UBNetworkingErrorO8internalyAcA020UBInternalNetworkingC0OcACmF","modules":[{"name":"UBFoundation"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation","doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingError"]]},"references":{"doc://UBFoundation/documentation/UBFoundation/UBNetworkingError/internal(_:)":{"role":"symbol","title":"UBNetworkingError.internal(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UBInternalNetworkingError","preciseIdentifier":"s:12UBFoundation25UBInternalNetworkingErrorO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"We cannot provide actionable information to the user. It is likely that something is broken on our end"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingError\/internal(_:)","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation\/ubnetworkingerror\/internal(_:)"},"doc://UBFoundation/documentation/UBFoundation/UBInternalNetworkingError":{"role":"symbol","title":"UBInternalNetworkingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBInternalNetworkingError"}],"abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBInternalNetworkingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBInternalNetworkingError"}],"url":"\/documentation\/ubfoundation\/ubinternalnetworkingerror"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkingError":{"role":"symbol","title":"UBNetworkingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkingError"}],"abstract":[{"type":"text","text":"Networking errors"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkingError"}],"url":"\/documentation\/ubfoundation\/ubnetworkingerror"},"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"}}}