{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkingTaskRecoveryStrategy"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworkingtaskrecoverystrategy"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryGroup"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryStrategy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Types that can recover a networking task failure. These objects are called after the validation process to allow for rectification. Once all strategies fails, then the completion block of the task fails. If one strategy finds a solution the no further strategies are called."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkingTaskRecoveryStrategy"}],"title":"UBNetworkingTaskRecoveryStrategy","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:12UBFoundation32UBNetworkingTaskRecoveryStrategyP","modules":[{"name":"UBFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"UBNetworkingTaskRecoveryStrategy"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryStrategy\/recoverTask(_:data:response:error:completion:)"]}],"references":{"doc://UBFoundation/documentation/UBFoundation/UBNetworkingTaskRecoveryStrategy/recoverTask(_:data:response:error:completion:)":{"role":"symbol","title":"recoverTask(_:data:response:error:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverTask"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UBURLDataTask","preciseIdentifier":"s:12UBFoundation13UBURLDataTaskC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UBNetworkingTaskRecoveryResult","preciseIdentifier":"s:12UBFoundation30UBNetworkingTaskRecoveryResultO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attempts a recovery of the failed task."}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryStrategy\/recoverTask(_:data:response:error:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/ubfoundation\/ubnetworkingtaskrecoverystrategy\/recovertask(_:data:response:error:completion:)"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkingTaskRecoveryStrategy":{"role":"symbol","title":"UBNetworkingTaskRecoveryStrategy","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkingTaskRecoveryStrategy"}],"abstract":[{"type":"text","text":"Types that can recover a networking task failure. These objects are called after the validation process to allow for rectification. Once all strategies fails, then the completion block of the task fails. If one strategy finds a solution the no further strategies are called."}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryStrategy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkingTaskRecoveryStrategy"}],"url":"\/documentation\/ubfoundation\/ubnetworkingtaskrecoverystrategy"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryGroup":{"role":"symbol","title":"UBNetworkTaskRecoveryGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkTaskRecoveryGroup"}],"abstract":[{"type":"text","text":"A group of data task failure recovery strategies"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkTaskRecoveryGroup"}],"url":"\/documentation\/ubfoundation\/ubnetworktaskrecoverygroup"},"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"}}}