{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"optionIndex"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions\/attemptrecovery(optionindex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions\/attemptRecovery(optionIndex:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attempt to recover from this error when the user selected the option at the given index. Returns true to indicate successful recovery, and false otherwise."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"optionIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"attemptRecovery(optionIndex:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:12UBFoundation28UBNetworkTaskRecoveryOptionsV07attemptD011optionIndexSbSi_tF","modules":[{"name":"UBFoundation"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation","doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions"]]},"references":{"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOptions":{"role":"symbol","title":"UBNetworkTaskRecoveryOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkTaskRecoveryOptions"}],"abstract":[{"type":"text","text":"A set of options to recover from a network task failure"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkTaskRecoveryOptions"}],"url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkTaskRecoveryOptions/attemptRecovery(optionIndex:)":{"role":"symbol","title":"attemptRecovery(optionIndex:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"optionIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Attempt to recover from this error when the user selected the option at the given index. Returns true to indicate successful recovery, and false otherwise."}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkTaskRecoveryOptions\/attemptRecovery(optionIndex:)","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation\/ubnetworktaskrecoveryoptions\/attemptrecovery(optionindex:)"}}}